# Generated by Django 4.2.17 on 2025-01-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('ceo', models.CharField(max_length=80)),
                ('origin_date', models.DateField()),
                ('origin_place', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('milage', models.CharField(max_length=30)),
                ('tank_capacity', models.FloatField(max_length=20)),
                ('colour', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=40)),
                ('cc', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='viewsapp.company')),
            ],
        ),
    ]
