# Generated by Django 4.2.17 on 2025-01-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='milage',
        ),
        migrations.AddField(
            model_name='products',
            name='mielage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='origin_date',
            field=models.IntegerField(),
        ),
    ]
