# Generated by Django 4.2.17 on 2025-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsapp', '0003_remove_products_brand_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AddField(
            model_name='products',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='pimage'),
        ),
    ]
