# Generated by Django 4.2.17 on 2025-01-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewsapp', '0004_company_logo_products_pimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pimage',
            new_name='pimgae',
        ),
    ]
