# Generated by Django 4.2.17 on 2025-01-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewsapp', '0005_rename_pimage_products_pimgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pimgae',
            new_name='pimage',
        ),
    ]
